### ISSUE TITLE
IndentationError: expected an indented block on line 1497

### ISSUE THREAD

**Issue by peileppe** [etherealxx/batchlinks-webui#18] opened 2023-03-24 10:24 UTC
Tested today (Fri Mar 24 11:23:53 CET 2023) 
This error prevent the module to be loaded in colab

  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/batchlinks-webui/scripts/batchlinks-downloader.py", line 1497
    if everymethod == False:
IndentationError: expected an indented block

**Comment by etherealxx** [comment] 2023-03-24 23:39
@peileppe @Th3K1n91 @nemuruibai
Sorry guys, i was sleeping earlier😣
Anyway, sadly i can't replicate it in Camenduru's colab. The extension just works fine. I also tested my extension everytime i update it. So this is pretty weird.

What version do you guys at? Have you updated with git pull yet? Is this a gdrive thing?

i also checked the code, there's no indentation error on that line at all. Really really weird..

**Comment by Th3K1n91** [comment] 2023-03-25 12:41
I found the issue :).

If you install and activate the extension on webui(automatic1111) it puts almost every "progress" function into a comment which is resulting an error on the else statement on line 1495, because line 1496 is a comment.

![Bild_2023-03-25_134126833](https://user-images.githubusercontent.com/63650014/227717880-5b6f2821-3e6b-4a4e-be61-f57230f6b984.png)

**Comment by etherealxx** [comment] 2023-03-25 14:51
@Th3K1n9! Thank you for the findings😁 though, would be nice if you push the fix into this repo instead👀

The fix is just adding `pass` to that line right?

> If you install and activate the extension on webui(automatic1111) it puts almost every "progress" function into a comment which is resulting an error on the else statement on line 1495, because line 1496 is a comment.

Anyway, it's kinda weird tho, it's supposed to that thing if --gradio-queue is off, which almost all camenduru's colab is queue on.

**Comment by etherealxx** [comment] 2023-03-25 15:31
Things that i needed is, how do you guys get this result? Which camenduru's colab did you guys use? because i can't replicate it somehow. Would be really really nice if you guys tell me, so we can fix it together.

**Comment by Th3K1n91** [comment] 2023-03-25 15:38
I don't use colab, I am using [Cloud GPU](https://vast.ai) with [this docker](https://hub.docker.com/r/runpod/stable-diffusion/tags) file, so I can't launch app with custom commands.

**Comment by etherealxx** [comment] 2023-03-25 16:07
Merged your fork, thanks.

**Closed by etherealxx** 2023-03-25 16:07 UTC

**Comment by peileppe** [comment] 2023-03-31 07:28
> @peileppe @Th3K1n91 @nemuruibai Sorry guys, i was sleeping earlierpersevere Anyway, sadly i can't replicate it in Camenduru's colab. The extension just works fine. I also tested my extension everytime i update it. So this is pretty weird.
> 
> What version do you guys at? Have you updated with git pull yet? Is this a gdrive thing?
> 
> i also checked the code, there's no indentation error on that line at all. Really really weird..

it was a colab setup, I fixed it manually

**Comment by etherealxx** [comment] 2023-03-31 07:38
> it was a colab setup, I fixed it manually 

Thanks for the clarification. The problem is also solved on the latest update now.

**Comment by peileppe** [comment] 2023-03-31 12:10
Your extension is super useful in colab, to download models, and loras faster
